title: Linzhi Hou
# tagline: Here is personal website of Linzhi Hou. Powered by Jekyll, based on the Minimal Mistakes theme.
# description: I am an Enthusiastic Computer Science and Technology student at THU. Passionate about coding, AI, and open-source projects.
# Comment out url when working locally to resolve base urls correctly
url: https://houlinzhi.com

# Owner/author information
owner:
  name: Linzhi Hou
  avatar: avatar.jpg
  bio: I am an Enthusiastic Computer Science and Technology student at THU. Passionate about coding, AI, and open-source projects.
  # cv: https://houlinzhi.com
  email: hlz23@mails.tsinghua.edu.cn
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  github: Zenith-Hlz
  bilibili: 667036156
  zhihu: https://www.zhihu.com/people/lin-zhi-cang-qiong
  # scholar: https://scholar.google.com/zenith
  # researchgate: https://www.researchgate.net/profile/zenith
  # twitter: zenith
  # linkedin: zenith
  # facebook: zenith
  # instagram: zenith

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Awards
    url: /awards/
  - title: Schoolwork
    url: /schoolwork/
  - title: Hobbies
    url: /hobbies/
  - title: Blogs
    url: /blogs/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
# disqus:
#   shortname: zenith

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

# Latest update in 2024/12/16 by Linzhi Hou.